-- ══════════════════════════════════════════════════════════════════════════════
-- datos_iniciales.sql  —  Datos mínimos para arrancar el sistema en producción
-- Ejecutar después de crear_bd.sql. Se puede relanzar: limpia y recarga solo
-- Componente, Tecnico y Usuario (no toca tablas operativas).
-- ══════════════════════════════════════════════════════════════════════════════

USE reparaciones;

SET SQL_SAFE_UPDATES  = 0;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Usuario;
TRUNCATE TABLE Tecnico;
TRUNCATE TABLE Componente;

SET FOREIGN_KEY_CHECKS = 1;

-- ── Usuarios iniciales ────────────────────────────────────────────────────────
-- Contraseña por defecto: cambiar tras el primer acceso
INSERT INTO Usuario (NOMBRE_USUARIO, PASSWORD, ROL, ID_TEC)
VALUES ('admin', '$2a$10$89OoWr1AD1dbESqCVGhGVOBWILu0ld117qcCSS68z1dH4k/A7MjBu', 'ADMIN', NULL);


-- ── Componentes (SKUs) ────────────────────────────────────────────────────────

-- Otros
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi8', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi8plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroise2020', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroix', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroixr', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroixs', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroixsmax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi11', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi11pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi11promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12mini', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13mini', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16e', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16plus', 0, 0);

-- Batería
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati8', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati8plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batise2020', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batix', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batixr', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batixs', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batixsmax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati11', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati11pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati11promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12mini', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13mini', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16e', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16plus', 0, 0);

-- Pantalla
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi11negraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi11pronegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi11promaxnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi12negraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi12mininegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi12promaxnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13negraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13mininegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13pronegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13promaxnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14negraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14pronegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14plusnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14promaxnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15negraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15plusnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15pronegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15promaxnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16negraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16enegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16pronegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16promaxnegraic', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16plusnegraic', 0, 0);

-- Cámara
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami8', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami8plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camise2020', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camix', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camixr', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camixs', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camixsmax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami11', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami11pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami11promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12mini', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13mini', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15plus', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16e', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16pro', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16promax', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16plus', 0, 0);

-- Chasis
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8silver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8gold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8spacegrey', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8productred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plussilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plusgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plusspacegrey', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plusproductred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaise2020black', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaise2020white', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaise2020productred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixspacegrey', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixssilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsspacegrey', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsmaxsilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsmaxspacegrey', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsmaxgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrproductred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixryellow', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrwhite', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrcoral', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrblack', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11black', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11green', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11yellow', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11purple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11productred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11white', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11progold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11prospacegray', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11prosilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promidnightgreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxspacegray', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxsilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxmidnightgreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12black', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12white', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12productred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12green', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12blue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12purple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniblack', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniwhite', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniproductred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12minigreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12minipurple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12prosilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12prographite', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12progold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12propacificblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxsilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxgraphite', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxpacificblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13productred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13starlight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13midnight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13pink', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13blue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13green', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13miniproductred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13ministarlight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13minimidnight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13miniblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13minipink', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13minigreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13prographite', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13progold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13prosilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13prosierrablue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13proalpinegreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxgraphite', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxsilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxsierrablue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxalpinegreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14midnight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14purple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14starlight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14productred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14blue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14yellow', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusmidnight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14pluspurple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusstarlight', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusproductred', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusyellow', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14prospaceblack', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14prosilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14progold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14prodeeppurple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxspaceblack', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxsilver', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxgold', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxdeeppurple', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15black', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15blue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15green', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15yellow', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15pink', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusblack', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusblue', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusgreen', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusyellow', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15pluspink', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15problacktitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15prowhitetitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15probluetitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15pronaturaltitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxblacktitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxwhitetitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxbluetitanium', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxnaturaltitanium', 0, 0);

-- Glass
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6sblanca', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6snegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6splusblanca', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6splusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7blanca', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7plusblanca', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8blanca', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8plusblanca', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gixnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gixrnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gixsmaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi11negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi11pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi11promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi12negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi12mininegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi12promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi13negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi13mininegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi13promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16enegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16promaxnegra', 0, 0);

-- Marco
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mcixnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mcixsnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mcixsmaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci11pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci11promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci12negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci12mininegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci12promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13mininegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15plusnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16negra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16promaxnegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16pronegra', 0, 0);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16enegra', 0, 0);

SET SQL_SAFE_UPDATES = 1;
